
/* PROGRAM VERSION */
#define DNSSTUB_VERSION "@DNSSTUB_VERSION@"

/* PROGRAM AUTHOR */
#define DNSSTUB_AUTHOR "@DNSSTUB_AUTHOR@"

/* CMAKE_CONFIGURE_TIME */
#define CMAKE_CONFIGURE_TIME "@CMAKE_CONFIGURE_TIME@"

/* ENABLE_XML */
#cmakedefine ENABLE_XML